### ISSUE TITLE
Low accuracy

### ISSUE THREAD

**Issue by gengstah** [happynoom/DeepTrade_keras#12]
Hi happynoom,

What was your accuracy when you trained the model. I tried to train it with my dataset and I got a very low accuracy (10-14%). Although with low accuracy, the model performs considerably well. 

- gengstah

**Comment by happynoom** [comment]
@gengstah The accuracy is supposed to be ignored, because the target of the output isn't predicting the y value, it is set to be our optimized operation, such as 1 for buy, 0 for sell. So, just ignore the accuracy.
