### ISSUE TITLE
Dropout on input_layer?

### ISSUE THREAD

**Issue by EmbraceLife** [happynoom/DeepTrade_keras#4]
Hi @happynoom 

Is this model at [L25](https://github.com/happynoom/DeepTrade_keras/blob/master/windpuller.py#L25) the best model you tried so far? 

Why do you use dropout on the first layer or input_layer? Wouldn't it be more usual to apply dropout on hidden layers? 

thanks

**Comment by happynoom** [comment]
Yes，I try some other models, and some of them reach -0.16 of loss too, but soon get over fitting. Then I add a dropout layer to input layer, and then to hidden layer. Maybe I add too much. I will try remove first dropout layer. Thank you very much. You question means much.

**Comment by EmbraceLife** [comment]
I am glad the question helps. To be more specific: the reason why it is not recommended to do dropout on Input layer is that we don't want to lose data; the reason why to apply dropout on hidden layer is to reduce overfitting while not losing data.

**Comment by happynoom** [comment]
It helps me a lot. I will do more experiments without input dropout layer. Thank you very much.
