### ISSUE TITLE
something wield on visualization site

### ISSUE THREAD

**Issue by EmbraceLife** [happynoom/DeepTrade_keras#6]
On the visualization profit section: 
Since 2017.06.26 up to 2017.06.28, the positions are 1s but no profit at all. It is not working properly right?
![](https://lh3.googleusercontent.com/d6k5UM1Y3oweA7oZeECC8WzPw5K2GbvFdStnwd_Wq1AN2Ovix9BnvzrFA93VrFTft1TXP7IUpjB-rAy4S7CMQeDRiqnvLf0zaFjeyYkuNEpc83lvUNoC_Y13kfzohGgliJT-dp-qvcNR8LEAKkzKGme1VV1z3KIBvqW7wMtEkCLaaaGUReZpP65VGXW8_Bh00SJXrwdQdJvHtlQv7JNucqHPnwGMde0xL14h5ATNXfBi9YA75dHGmib2DQ9qBNvUtbMYKruFe_-7tKJtljbtDM6o3gi5s2QetATtfh7w57mYKIjp2qnz38Qj1uuEeC9ibz4DoDwzx4FQdQCAndWCZ1vBG2LW3Y6ZeIW_YHaqFVEToHtknDnbVG4slj5wHOD_3Cg66MSyzrHRWO2pvclM88EXwJ416ts0gtWXzeVonn4zwgH5HfdflIpaNv-Fpc7oeXVxzw-cSi8jAJrk1EQsZRXndB9ispmfDZCahlwnwojKwE4NHF8TXZJ0k8O2ihr74QsQ_fjgoCZPxHfhC7d_IHa2Tng0ytuYRDU0AlVB_IG5YY2LZHKm1yf0Hl-9tK-EIyGzxMoQNP0sVFJjLk0Ro39gPS_fqXVRTr6ubMkklx8mLDF5uHn3=w214-h604-no)

**Comment by happynoom** [comment]
@EmbraceLife Sorry, I forgot to run profit calculation script. I think I should set a crontab or something. Thank you for the alert.
