### ISSUE TITLE
Design of model skeleton and feature selection?

### ISSUE THREAD

**Issue by EmbraceLife** [happynoom/DeepTrade_keras#7]
Hi @happynoom 

I wonder how do you come up with this specific kind of model structure or skeleton. Could you explain the rationality for designing the model in such a structure? 

Also, you have chose 61 indicators and normalized them in certain ways. Could you explain why you choose those indicators and why you normalize them in such a way? 

Thanks

**Comment by peterhanneman** [comment]
Hey @EmbraceLife

The feature vector normalization improves the performance of the neural network by creating a well defined upper and lower bound for each input.

The chosen indicators are some of the most commonly used for performing rudimentary technical analysis on candlestick data.  The underlying ```ta-lib``` library supports a multitude of other unimplemented indicators but more importantly _**none**_ of the parameters to those functions have yet been tuned for the target one day forecast.  There is huge room for improvement here.  But one should not limit the scope of their search to what ```ta-lib``` supports as there are thousands of other well documented algorithms with more powerful predictive power.
