### ISSUE TITLE
What does value of pred  represent?

### ISSUE THREAD

**Issue by kaishijeng** [happynoom/DeepTrade_keras#9]
I print out pred below and values don't look like the price of prediction of next day.    
pred = saved_wp.predict(test_set.images, 1024).
How can I get prediction of next day stock price?

Thanks,

**Comment by happynoom** [comment]
You should see the readme definitely.

**Comment by kaishijeng** [comment]
I read the readme and understand the meaning of prediction value.
I can see how to use prediction to sell a stock. But it is not clear to me how  to use prediction to make a decision to sell a stock.
Comment?

Thanks,
